import { Link } from "@tanstack/react-router";
import { ArrowRight, CircleAlert, Clock3, ShieldAlert } from "lucide-react";
import type { Incident, Severity, Status } from "@/lib/security";

const severityStyles: Record<Severity, string> = { Critical: "bg-danger-soft text-danger", High: "bg-warning-soft text-warning", Medium: "bg-info-soft text-info", Low: "bg-success-soft text-success" };
const statusStyles: Record<Status, string> = { Open: "text-danger", "In Progress": "text-info", Resolved: "text-success", Closed: "text-muted-foreground" };
export function SeverityBadge({ severity }: { severity: Severity }) { return <span className={`inline-flex items-center rounded px-2.5 py-1 text-[11px] font-bold ${severityStyles[severity]}`}>{severity}</span>; }
export function StatusLabel({ status }: { status: Status }) { return <span className={`inline-flex items-center gap-1.5 text-xs font-semibold ${statusStyles[status]}`}><span className="size-1.5 rounded-full bg-current" />{status}</span>; }
export function formatDate(value: string) { const date = new Date(value.replace(" ", "T") + (value.includes("Z") ? "" : "Z")); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }
export function PreviewNotice() { return <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-md border border-info/20 bg-info-soft px-4 py-3"><div className="flex items-center gap-2.5 text-sm text-info"><CircleAlert size={17} className="shrink-0" /><span><strong>Preview data</strong> — connect your backend to see and manage real incidents.</span></div><Link to="/settings" className="inline-flex items-center gap-1 text-xs font-bold text-info hover:underline">Connect backend <ArrowRight size={14} /></Link></div>; }
export function ErrorNotice({ message, onRetry }: { message: string; onRetry: () => void }) { return <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-md border border-danger/20 bg-danger-soft px-4 py-3"><p className="flex items-center gap-2 text-sm text-danger"><ShieldAlert size={17} />Could not load incidents: {message}</p><button className="text-xs font-bold text-danger underline" onClick={onRetry}>Try again</button></div>; }
export function IncidentTable({ incidents, onSelect, compact = false }: { incidents: Incident[]; onSelect?: (incident: Incident) => void; compact?: boolean }) {
  return <div className="overflow-x-auto rounded-md border border-border bg-card"><table className="w-full min-w-165 text-left"><thead><tr className="border-b border-border bg-surface text-[11px] font-bold uppercase tracking-[0.08em] text-muted-foreground"><th className="px-5 py-4">Incident</th><th className="px-4 py-4">Severity</th><th className="px-4 py-4">Status</th><th className="px-4 py-4">Date</th><th className="px-5 py-4 text-right"> </th></tr></thead><tbody>{incidents.length ? incidents.slice(0, compact ? 5 : undefined).map((incident) => <tr key={incident.id} onClick={() => onSelect?.(incident)} className={`border-b border-border/75 last:border-b-0 ${onSelect ? "cursor-pointer hover:bg-surface" : ""}`}><td className="px-5 py-4"><div className="font-semibold text-sm text-foreground">{incident.title}</div><div className="mt-1 text-xs text-muted-foreground">INC-{incident.id}</div></td><td className="px-4 py-4"><SeverityBadge severity={incident.severity} /></td><td className="px-4 py-4"><StatusLabel status={incident.status} /></td><td className="px-4 py-4 text-xs text-muted-foreground">{formatDate(incident.created_at)}</td><td className="px-5 py-4 text-right text-muted-foreground"><ArrowRight size={16} className="ml-auto" /></td></tr>) : <tr><td colSpan={5} className="px-5 py-14 text-center"><Clock3 size={24} className="mx-auto mb-3 text-muted-foreground" /><p className="text-sm font-semibold">No incidents found</p><p className="mt-1 text-xs text-muted-foreground">Try another search or filter.</p></td></tr>}</tbody></table></div>;
}
